09-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)600: ValidacionDeToken: No apareció CUIT en lista de relaciones: 20078131455
09-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)602: No existen datos en nuestros registros para los parametros ingresados.
09-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)602: No existen datos en nuestros registros para los parametros ingresados.
09-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)Orden:110051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
09-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)Orden:110051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
09-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)Orden:110070: Si ImpNeto es mayor a 0 el objeto IVA es obligatorio.602: No existen datos en nuestros registros para los parametros ingresados.
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)600: ValidacionDeToken: No apareció CUIT en lista de relaciones: 20172716912
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)600: ValidacionDeToken: No apareció CUIT en lista de relaciones: 20172716912
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,27)Orden:110070: Si ImpNeto es mayor a 0 el objeto IVA es obligatorio.602: No existen datos en nuestros registros para los parametros ingresados.
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,1)Orden:1265110070: Si ImpNeto es mayor a 0 el objeto IVA es obligatorio.602: No existen datos en nuestros registros para los parametros ingresados.
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,1)Orden:1265110070: Si ImpNeto es mayor a 0 el objeto IVA es obligatorio.602: No existen datos en nuestros registros para los parametros ingresados.
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,1)Server was unable to read request. ---> There is an error in XML document (5, 1536). ---> Input string was not in a correct format.
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,1)Server was unable to read request. ---> There is an error in XML document (5, 1536). ---> Input string was not in a correct format.
18-03-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,1)Server was unable to read request. ---> There is an error in XML document (5, 1536). ---> Input string was not in a correct format.
06-04-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,1)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,1,1)Fecha Ulti: 16-03-2016El CUIT consultado (20054940077)no coincide con el del comprobante (20169604747)602: No existen datos en nuestros registros para los parametros ingresados.
18-04-2016 , Version 2.10d InstallDir C:\PROGRA~1\PyAfipWs1.16d C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,10)Fecha Ulti: 07-04-2016El CUIT consultado (20054940077)no coincide con el del comprobante (20169604747)
18-04-2016 , Version 2.10d InstallDir C:\PROGRA~1\PyAfipWs1.16d C:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 150, in capturar_errores_wrapper
  File "utils.pyc", line 377, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 150, in capturar_errores_wrapper
  File "utils.pyc", line 377, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 150, in capturar_errores_wrapper
  File "utils.pyc", line 377, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-04-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-04-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-04-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-04-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 152, in capturar_errores_wrapper
  File "utils.pyc", line 375, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

18-04-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,13)Fecha Ulti: 18-04-2016ERROR AL SOLICITARCAEEl nro de comprobante autorizado 2 ya se encontraba informado.El ultimo autorizado por Afip es 13El CUIT consultado (20054940077)no coincide con el del comprobante (20169604747)
06-05-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,15)Fecha Ulti: 18-04-2016Codigo error afip:0Numero de Error: 107Mensaje de Error: Linea de codigo de error: IF nImpTotal <> nTotalCompProcedimiento: robotconsul_procesoError VFP: Incompatibilidad entre el tipo de operador y el tipo de operando.Exepción: Traceback: 
06-05-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,15)Fecha Ulti: 18-04-2016WSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,15)Fecha Ulti: 18-04-2016Codigo error afip:0Numero de Error: 1734Mensaje de Error: PATHORIGENLinea de codigo de error: IF FILE(this.Pathorigen+cName+".CA0")Procedimiento: cambiarmoduloError VFP: No se encuentra la propiedad PATHORIGEN.Exepción: Traceback: 
06-05-2016 , Version 2.10b HomologaciónInstallDir C:\PROGRA~1\PyAfipWs1.16d HomologaciónC:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,15)Fecha Ulti: 18-04-2016WSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,15)Fecha Ulti: 18-04-2016Codigo error afip:0Numero de Error: 1924Mensaje de Error: PARENTLinea de codigo de error: IF FILE(this.Parent.Pathorigen+cName+".CA0")Procedimiento: cambiarmoduloError VFP: PARENT no es un objeto.Exepción: Traceback: 
