11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,7)WSFE.CompUltimoAutorizado(6,7)WSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,7)WSFE.CompUltimoAutorizado(6,7)WSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
11-06-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,7)WSFE.CompUltimoAutorizado(6,7)WSFE.CompUltimoAutorizado(3,4)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
31-08-2018 , Version 2.11a InstallDir C:\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 7116:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
7116:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
7116:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 7116:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
7116:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
7116:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 7116:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
7116:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
7116:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


31-08-2018 , Version 2.11a InstallDir C:\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 7116:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
7116:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
7116:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 7116:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
7116:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
7116:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 7116:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
7116:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
7116:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


31-08-2018 , Version 2.11a InstallDir C:\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 3064:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
3064:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
3064:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 3064:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
3064:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
3064:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 3064:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
3064:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
3064:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


31-08-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OK
31-08-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,6012)Fecha Ulti: 31-08-2018Orden:11000004077210152: Campo CbteFch comprendido en el rango N+5 siendo N la fecha de envÃ­o del pedido de autorizaciÃ³n para 1 - Productos, CbteFch no podrÃ¡ exceder el mes de la fecha N (fecha de envÃ­o del pedido de autorizacion).
28-09-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

..Exepción: SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


28-09-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

..Exepción: SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


28-09-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

..Exepción: SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5424:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5424:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5424:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


28-09-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
..Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
28-09-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
..Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
28-09-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,0)Fecha Ulti: 28-09-2018Llamada: WSFE.CAESolicitarOrden:11000000003610019: El campo Id en AlicIVA es obligatorio y debe ser alguno de los devueltos por el metodo FEParamGetTiposIva.
20-11-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,161)Fecha Ulti: 19-11-2018ERROR AL SOLICITARCAEEl nro de comprobante autorizado48 ya se encontraba informado.El ultimo autorizado por Afip es161El Total consultado (3425.50)no coincide con el del comprobante (15.00)El CUIT consultado (30999009332) no coincide con el del comprobante en afip(0)
30-11-2018 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\PyAfipWsCertificados DesarrolloNo existe el Certificado.crt               Ruta: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Certificado.crt               Codigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cruta + this.hcrt, cruta + this.hkey)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Certificado.crt               
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Certificado.crt               
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Certificado.crt               

03-12-2018 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA AlmacenadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,172)Fecha Ulti: 03-12-2018Llamada: WSFE.CompConsultar602: No existen datos en nuestros registros para los parametros ingresados.
03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cFileCRT, cRuta + cFileKey) && Cert. DemoProcedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   

03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cFileCRT, cRuta + cFileKey) && Cert. DemoProcedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   

03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cFileCRT, cRuta + cFileKey) && Cert. DemoProcedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Garrone.crt                   

03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ok = WSAA.Conectar(cache, url_wsdl, proxy)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
.Exepción: TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)

03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ok = WSAA.Conectar(cache, url_wsdl, proxy)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
.Exepción: TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)

03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ok = WSAA.Conectar(cache, url_wsdl, proxy)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
.Exepción: TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)

03-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ok = WSAA.Conectar(cache, url_wsdl, proxy)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
.Exepción: TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 140, in __init__
  File "pysimplesoap\client.pyc", line 469, in wsdl_parse
  File "pysimplesoap\client.pyc", line 455, in fetch
  File "httplib2\__init__.pyc", line 2135, in request
  File "httplib2\__init__.pyc", line 1796, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1701, in _conn_request
  File "httplib2\__init__.pyc", line 1368, in connect
TypeError: _ssl_wrap_socket() takes exactly 5 arguments (7 given)

05-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
05-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6436:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6436:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6436:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 6436:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6436:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6436:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6436:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6436:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6436:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


05-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
05-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA AlmacenadoWSFE Version 1.22a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
05-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
05-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.22a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
06-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsError sw_iniciar pero continua Ya posee un TA activoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_wsfe_conectarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "utils.pyc", line 391, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
..Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "utils.pyc", line 391, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

06-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
12-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
04-12-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
31-01-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Tamburini.crt                                     
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Tamburini.crt                                     
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Tamburini.crt                                     

31-01-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)601: CUIT representada no incluida en Token
05-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 25516:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
25516:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
25516:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 25516:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
25516:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
25516:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 25516:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
25516:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
25516:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


05-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
05-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
07-02-2021 , Iniciando FeedBack
07-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Cuadrado.crt                  
..Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Cuadrado.crt                  

07-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
09-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
26-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
26-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
26-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
05-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,17322)Fecha Ulti: 05-03-2021Orden:11000000047610020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
05-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,17322)Fecha Ulti: 05-03-2021Orden:11000000047610020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
12-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
12-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
17-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1164)Fecha Ulti: 17-03-2021Llamada: WSFE.CAESolicitarOrden:11000000028610020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
17-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1164)Fecha Ulti: 17-03-2021Llamada: WSFE.CAESolicitarOrden:11000000028710020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
17-03-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1164)Fecha Ulti: 17-03-2021Llamada: WSFE.CAESolicitarOrden:11000000028810020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
01-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(3,11,967)Fecha Ulti: 31-03-2021Orden:11000000211210213: Si informa el campo CbteAsoc.CbteFch, debe corresponde a una fecha valida con formato YYYYMMDD.
06-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,1)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30716456117
06-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
06-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,1)600: ValidacionDeToken: No aparecio CUIT en lista de relaciones: 30716456117
06-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Petrolanda.crt                
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Petrolanda.crt                
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Gestion.key                   , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\Petrolanda.crt                

08-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

08-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

08-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

08-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1341)Fecha Ulti: 09-04-21ERROR AL SOLICITARCAEEl nro de comprobante autorizado1283 ya se encontraba informado.El ultimo autorizado por Afip es1341El Total consultado (13057.95)no coincide con el del comprobante (95.34)El CUIT consultado (20350324977) no coincide con el del comprobante en afip(0)
09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

09-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

15-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

17-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
22-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 219, in call
  File "pysimplesoap\client.pyc", line 264, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1263, in _conn_request
ServerNotFoundError: Unable to find the server at wsaa.afip.gov.ar
.Exepción: ServerNotFoundError: Unable to find the server at wsaa.afip.gov.ar
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 219, in call
  File "pysimplesoap\client.pyc", line 264, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1263, in _conn_request
ServerNotFoundError: Unable to find the server at wsaa.afip.gov.ar

22-04-21 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privada                       , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\cuadrado.crt                  

23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1638)Fecha Ulti: 23-04-2021Orden:11000000683210044: El campo ImpOpEx (importe exento) no puede ser menor a cero (0).
23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(3,11,1016)Fecha Ulti: 23-04-2021Orden:11000000548310058: De enviarse el tag CbtesAsoc debe enviarse PtoVta mayor a 0
23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(3,11,1016)Fecha Ulti: 23-04-2021WSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1638)Fecha Ulti: 23-04-2021Orden:11000000683210044: El campo ImpOpEx (importe exento) no puede ser menor a cero (0).
23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1638)Fecha Ulti: 23-04-2021Orden:11000000683210044: El campo ImpOpEx (importe exento) no puede ser menor a cero (0).
23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,1638)Fecha Ulti: 23-04-2021Orden:11000000683210043: El campo ImpTotConc (Importe neto no gravado) no puede ser menor a cero (0).
23-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 99998
