06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 298, in wsdl_call
  File "pysimplesoap\client.pyc", line 292, in get_operation
RuntimeError: Operation loginCms not found in WSDL: Service/Port Type: (u'PersonaServiceA5', u'PersonaServiceA5Port')
.Exepción: RuntimeError: Operation loginCms not found in WSDL: Service/Port Type: (u'PersonaServiceA5', u'PersonaServiceA5Port')
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 298, in wsdl_call
  File "pysimplesoap\client.pyc", line 292, in get_operation
RuntimeError: Operation loginCms not found in WSDL: Service/Port Type: (u'PersonaServiceA5', u'PersonaServiceA5Port')

06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.untrusted: Certificado no emitido por AC de confianza
.Exepción: ns1:cms.cert.untrusted: Certificado no emitido por AC de confianzaTraceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 11Linea de codigo de error: IF CTOT(This.Tiempoexpiracion) > DATETIME()Procedimiento: sw_iniciarError VFP: El valor, tipo o número de argumentos no es válido para la función.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 11Linea de codigo de error: IF CTOT(This.Tiempoexpiracion) > DATETIME()Procedimiento: sw_iniciarError VFP: El valor, tipo o número de argumentos no es válido para la función.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 11Linea de codigo de error: IF CTOT(This.Tiempoexpiracion) > DATETIME()Procedimiento: sw_iniciarError VFP: El valor, tipo o número de argumentos no es válido para la función.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 107Linea de codigo de error: CASE cWebService='wsfe'Procedimiento: ta_guardarError VFP: Incompatibilidad entre el tipo de operador y el tipo de operando.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Codigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Conectar(wsdl)Procedimiento: sw_padrona5_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 139, in __init__
  File "pysimplesoap\client.pyc", line 457, in wsdl_parse
  File "pysimplesoap\client.pyc", line 450, in fetch
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: u'https:'
.Exepción: WindowsError: [Error 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: u'https:'
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 139, in __init__
  File "pysimplesoap\client.pyc", line 457, in wsdl_parse
  File "pysimplesoap\client.pyc", line 450, in fetch
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: u'https:'

22-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
22-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: PADRON.Dummy()Procedimiento: sw_padrona5_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "ws_sr_padron.pyc", line 92, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: soap:Server: Fault occurred while processing.
.Exepción: Traceback: 
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado ws_sr_padron_a5WSSrPadronA5 1.03_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-33717617-9Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 212, in Consultar
KeyError: 'error'
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-33717617-9Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 212, in Consultar
KeyError: 'error'
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-33717617-9Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 212, in Consultar
KeyError: 'error'
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperado
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-35034096-4Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 216, in Consultar
AttributeError: 'list' object has no attribute 'get'
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-17271691-2Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 251, in Consultar
KeyError: 'idImpuesto'
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-33717617-9Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 216, in Consultar
AttributeError: 'list' object has no attribute 'get'
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-35034096-4Error :La clave ingresada no es una CUITLlamada: PADRON.Consultar ERROR NO DEFINIDO
26-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexxion ExistosaConsultando AFIP online...20-33717617-9Error :Tu Constancia se encuentra bloqueada. El 30-nov-2018 venciÃ³ el plazo para constituir el domicilio fiscal electrÃ³nico. Constituilo para desbloquearla.Llamada: PADRON.Consultar ERROR NO DEFINIDO
05-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


05-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


05-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 9336:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
9336:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
9336:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


05-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
05-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
17-07-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...20-14683134-7Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 198, in Consultar
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: soap:Server: Este token no le permite actuar en representacion de la CUIT 30714171611
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
17-07-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...20-14683134-7Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 198, in Consultar
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: soap:Server: Este token no le permite actuar en representacion de la CUIT 30714171611
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
03-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 8640:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
8640:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
8640:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 8640:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
8640:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
8640:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 8640:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
8640:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
8640:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


03-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 8640:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
8640:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
8640:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 8640:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
8640:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
8640:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 8640:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
8640:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
8640:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


04-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: c:\aplicaciones\afip\Gestion.key                   , c:\aplicaciones\afip\UrqProd.crt                   
.Exepción: RuntimeError: Archivos no encontrados: c:\aplicaciones\afip\Gestion.key                   , c:\aplicaciones\afip\UrqProd.crt                   
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: c:\aplicaciones\afip\Gestion.key                   , c:\aplicaciones\afip\UrqProd.crt                   

04-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


04-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


04-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6416:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6416:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6416:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


04-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
04-09-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
04-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6972:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6972:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6972:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 6972:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6972:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6972:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6972:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6972:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6972:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


04-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6972:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6972:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6972:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 6972:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6972:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6972:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 101, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 6972:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
6972:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
6972:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


12-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
12-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicio
.Exepción: ns1:coe.notAuthorized: Computador no autorizado a acceder al servicioTraceback: 
31-08-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado ws_sr_padron_a5WSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...30-70820769-8Error :No responde al requerimientoLlamada: PADRON.Consultar ERROR NO DEFINIDO
31-08-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...30-70820769-8Error :No responde al requerimientoLlamada: PADRON.Consultar ERROR NO DEFINIDO
