06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 298, in wsdl_call
  File "pysimplesoap\client.pyc", line 292, in get_operation
RuntimeError: Operation loginCms not found in WSDL: Service/Port Type: (u'PersonaServiceA5', u'PersonaServiceA5Port')
.Exepción: RuntimeError: Operation loginCms not found in WSDL: Service/Port Type: (u'PersonaServiceA5', u'PersonaServiceA5Port')
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 298, in wsdl_call
  File "pysimplesoap\client.pyc", line 292, in get_operation
RuntimeError: Operation loginCms not found in WSDL: Service/Port Type: (u'PersonaServiceA5', u'PersonaServiceA5Port')

06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_cuit_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 263, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.untrusted: Certificado no emitido por AC de confianza
.Exepción: ns1:cms.cert.untrusted: Certificado no emitido por AC de confianzaTraceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 11Linea de codigo de error: IF CTOT(This.Tiempoexpiracion) > DATETIME()Procedimiento: sw_iniciarError VFP: El valor, tipo o número de argumentos no es válido para la función.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 11Linea de codigo de error: IF CTOT(This.Tiempoexpiracion) > DATETIME()Procedimiento: sw_iniciarError VFP: El valor, tipo o número de argumentos no es válido para la función.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 11Linea de codigo de error: IF CTOT(This.Tiempoexpiracion) > DATETIME()Procedimiento: sw_iniciarError VFP: El valor, tipo o número de argumentos no es válido para la función.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:0Numero de Error: 107Linea de codigo de error: CASE cWebService='wsfe'Procedimiento: ta_guardarError VFP: Incompatibilidad entre el tipo de operador y el tipo de operando.Exepción: Traceback: 
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5
06-04-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Codigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Conectar(wsdl)Procedimiento: sw_padrona5_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 139, in __init__
  File "pysimplesoap\client.pyc", line 457, in wsdl_parse
  File "pysimplesoap\client.pyc", line 450, in fetch
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: u'https:'
.Exepción: WindowsError: [Error 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: u'https:'
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 277, in Conectar
  File "pysimplesoap\client.pyc", line 139, in __init__
  File "pysimplesoap\client.pyc", line 457, in wsdl_parse
  File "pysimplesoap\client.pyc", line 450, in fetch
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: u'https:'

