15-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     

15-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     

