15-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     

15-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 97, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\privadak.key                  , J:\XSOFTSQL\PROYECTOS\DISTRIBUIDORA\AfipCert\kleja.crt                     

01-03-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,762)Fecha Ulti: 01-03-2018Orden:11000001811010051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
01-03-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,762)Fecha Ulti: 01-03-2018Orden:11000001811010051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
01-03-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,762)Fecha Ulti: 01-03-2018Orden:11000001811010020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
02-03-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

02-03-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,769)Fecha Ulti: 02-03-2018Llamada: WSFE.CAESolicitarOrden:11000001856710061: La suma de los campos BaseImp en AlicIva debe ser igual al valor ingresado en ImpNeto.
06-04-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

06-04-2018 , Version 2.11a InstallDir C:\PyAfipWs1.18a C:\PyAfipWsappserver status OKdbserver status OKauthserver status OK
23-05-2018 , Version 2.11a InstallDir C:\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 3676:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
3676:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
3676:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 3676:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
3676:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
3676:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 3676:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
3676:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
3676:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


