12-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,0)Fecha Ulti: 12-02-2021Llamada: WSFE.CompConsultar500: Error interno de aplicación: - Metodo FECompConsultar
12-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,6805)Fecha Ulti: 12-02-2021ERROR AL SOLICITARCAEEl nro de comprobante autorizado6805 ya se encontraba informado.El ultimo autorizado por Afip es6805El Total consultado (349.50)no coincide con el del comprobante (35.00)
12-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion ExistosaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: WSFE.Dummy()Procedimiento: sw_wsfe_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.Exepción: AttributeError: Tag not found: Body (No elements found)
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 125, in Dummy
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

12-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
12-02-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,11)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,11,6805)Fecha Ulti: 12-02-2021ERROR AL SOLICITARCAEEl nro de comprobante autorizado6805 ya se encontraba informado.El ultimo autorizado por Afip es6805El Total consultado (349.50)no coincide con el del comprobante (35.00)
12-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,10)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
12-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,12)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(3,12,158)Fecha Ulti: 30-03-2021Llamada: WSFE.CAESolicitarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cCAESolicitar = WSFE.CAESolicitar()Procedimiento: solicitar_procesoError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 288, in CAESolicitar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1572). ---> Input string was not in a correct format.
.Exepción: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1572). ---> Input string was not in a correct format.Traceback: Llamada: WSFE.CAESolictar Server was unable to read request. ---> There is an error in XML document (5, 1572). ---> Input string was not in a correct format.
30-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
30-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(3,12)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(3,12,161)Fecha Ulti: 15-04-2021Llamada: WSFE.CAESolicitarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cCAESolicitar = WSFE.CAESolicitar()Procedimiento: solicitar_procesoError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 288, in CAESolicitar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1566). ---> Input string was not in a correct format.
.Exepción: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1566). ---> Input string was not in a correct format.Traceback: Llamada: WSFE.CAESolictar Server was unable to read request. ---> There is an error in XML document (5, 1566). ---> Input string was not in a correct format.
03-05-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(8,12)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(8,12,55)Fecha Ulti: 29-04-2021Llamada: WSFE.CAESolicitarOrden:11000097286510210:  PtoVta:11 - Tipo:6 - Nro:14438 - Comprobante electronico con fecha emision posterior a la fecha de emision del comprobante que se esta autorizando. Si es posterior, debe estar dentro del mismo periodo YYYYMM
