22-12-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\ElCoyote.crt                                                                              
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\ElCoyote.crt                                                                              
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\ElCoyote.crt                                                                              

22-12-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\ElCoyote.crt                                                                              
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\ElCoyote.crt                                                                              
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\ElCoyote.crt                                                                              

26-04-2022 17:35:06 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,1)Fecha Ulti: 26-04-2022ERROR AL SOLICITARCAEEl nro de comprobante autorizado 1 ya se encontraba informado.El ultimo autorizado por Afip es 1El Total consultado (0.00)no coincide con el del comprobante (1040.60)El CUIT consultado (20925289109)no coincide con el del comprobante (30716216183)
27-04-2022 14:42:41 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,56)Fecha Ulti: 26-04-2022Codigo error afip:*****Numero de Error: 1429Linea de codigo de error: cCAESolicitar = WSFE.CAESolicitar()Procedimiento: lote_procesoError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 288, in CAESolicitar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1208). ---> Input string was not in a correct format.
.Exepción: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1208). ---> Input string was not in a correct format.Traceback: Server was unable to read request. ---> There is an error in XML document (5, 1208). ---> Input string was not in a correct format.
27-04-2022 14:45:16 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,3,56)Fecha Ulti: 26-04-2022Codigo error afip:*****Numero de Error: 1429Linea de codigo de error: cCAESolicitar = WSFE.CAESolicitar()Procedimiento: lote_procesoError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 288, in CAESolicitar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1208). ---> Input string was not in a correct format.
.Exepción: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1208). ---> Input string was not in a correct format.Traceback: Server was unable to read request. ---> There is an error in XML document (5, 1208). ---> Input string was not in a correct format.
