06-04-2019 12:02:23 , VERCUIT_WS.BTTNNOENTER1.CLICK, Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  Fi;Linea : ok = PADRON.Consultar(cDocumento);Error :       1429;Ultimo Alias Activo: ;Ultimo registro:          0 ;DBF: ;Ultimo Control activo: 
06-04-2019 12:02:23 , Pila de llamadas
06-04-2019 12:02:23 , Programa    : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
06-04-2019 12:02:23 , Objeto      : vercuit_ws.bttnnoenter1.click
06-04-2019 12:02:23 , Base Objeto : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
06-04-2019 12:02:23 , Nº de Linea :          1
06-04-2019 12:02:23 , En el Fuente: thisform.VerCuit()
06-04-2019 12:02:23 , Programa    : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
06-04-2019 12:02:23 , Objeto      : vercuit_ws.vercuit
06-04-2019 12:02:23 , Base Objeto : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
06-04-2019 12:02:23 , Nº de Linea :          5
06-04-2019 12:02:23 , En el Fuente: 	.oWsAFIP.cuit_consultar()
06-04-2019 12:02:23 , Programa    : j:\xsoftsql\desarrollo\clases\onegocio.vct
06-04-2019 12:02:23 , Objeto      : vercuit_ws.owsafip.cuit_consultar
06-04-2019 12:02:23 , Base Objeto : j:\xsoftsql\desarrollo\clases\onegocio.vct
06-04-2019 12:02:23 , Nº de Linea :          7
06-04-2019 12:02:23 , En el Fuente: 	this.cuit_proceso()
06-04-2019 12:02:23 , Programa    : j:\xsoftsql\desarrollo\clases\onegocio.vct
06-04-2019 12:02:23 , Objeto      : vercuit_ws.owsafip.cuit_proceso
06-04-2019 12:02:23 , Base Objeto : j:\xsoftsql\desarrollo\clases\onegocio.vct
06-04-2019 12:02:23 , Nº de Linea :          9
06-04-2019 12:02:23 , En el Fuente: ok = PADRON.Consultar(cDocumento)
06-04-2019 12:02:23 , Fin
