22-04-2019 19:19:52 , VERCUIT_WS.BTTNNOENTER1.CLICK, Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  Fi;Linea : ok = PADRON.Consultar(cDocumento);Error :       1429;Ultimo Alias Activo: ;Ultimo registro:          0 ;DBF: ;Ultimo Control activo: 
22-04-2019 19:19:52 , Pila de llamadas
22-04-2019 19:19:52 , Programa    : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
22-04-2019 19:19:52 , Objeto      : vercuit_ws.bttnnoenter1.click
22-04-2019 19:19:53 , Base Objeto : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
22-04-2019 19:19:53 , Nº de Linea :          1
22-04-2019 19:19:53 , En el Fuente: thisform.VerCuit()
22-04-2019 19:19:53 , Programa    : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
22-04-2019 19:19:53 , Objeto      : vercuit_ws.vercuit
22-04-2019 19:19:53 , Base Objeto : j:\xsoftsql\desarrollo\forms\vercuit_ws.sct
22-04-2019 19:19:53 , Nº de Linea :          5
22-04-2019 19:19:53 , En el Fuente: 	.oWsAFIP.cuit_consultar()
22-04-2019 19:19:53 , Programa    : j:\xsoftsql\desarrollo\clases\onegocio.vct
22-04-2019 19:19:53 , Objeto      : vercuit_ws.owsafip.cuit_consultar
22-04-2019 19:19:53 , Base Objeto : j:\xsoftsql\desarrollo\clases\onegocio.vct
22-04-2019 19:19:53 , Nº de Linea :          8
22-04-2019 19:19:53 , En el Fuente: 	this.cuit_proceso_2()
22-04-2019 19:19:53 , Programa    : j:\xsoftsql\desarrollo\clases\onegocio.vct
22-04-2019 19:19:53 , Objeto      : vercuit_ws.owsafip.cuit_proceso_2
22-04-2019 19:19:53 , Base Objeto : j:\xsoftsql\desarrollo\clases\onegocio.vct
22-04-2019 19:19:53 , Nº de Linea :         18
22-04-2019 19:19:53 , En el Fuente: 	ok = PADRON.Consultar(cDocumento)
22-04-2019 19:19:53 , Fin
